#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

ln -sf $DOTFILES/.bashrc $HOME/.bashrc
ln -sf $DOTFILES/.gitconfig $HOME/.gitconfig
ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

