#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

# Bash
ln -sf $DOTFILES/bash/bashrc $HOME/.bashrc

# Vim
ln -sf $DOTFILES/vim/vimrc.plug $HOME/.vimrc.plug
ln -sf $DOTFILES/vim/vimrc $HOME/.vimrc

# Git
ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig

# Tmux
ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

